name: Build, Package, and Deploy to IIS

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0'

    - name: Restore Dependencies
      run: dotnet restore

    - name: Build Project
      run: dotnet build --configuration Release --no-restore

    - name: Publish Project
      run: dotnet publish --configuration Release --output ./publish

    - name: Compress Output to ZIP
      run: Compress-Archive -Path ./publish/* -DestinationPath ./build-package.zip
      shell: pwsh

    - name: Upload build package as artifact
      uses: actions/upload-artifact@v4
      with:
        name: build-package
        path: ./build-package.zip

    - name: Deploy to IIS
      run: |
        $artifactPath = "$env:GITHUB_WORKSPACE\build-package.zip"
        $deployFolder = "D:\Publish\SamplePipeline\package"

        if (!(Test-Path $deployFolder)) { New-Item -ItemType Directory -Path $deployFolder }

        Expand-Archive -Path $artifactPath -DestinationPath $deployFolder -Force

        Write-Host "Deployment completed successfully to $deployFolder"
      shell: pwsh
