name: Build, Package, and Store ZIP for Later Deployment

on:
  push:
    branches:
      - master

jobs:
  build-package:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0'

    - name: Restore Dependencies
      run: dotnet restore

    - name: Build Project
      run: dotnet build --configuration Release --no-restore

    - name: Publish Project
      run: dotnet publish --configuration Release --output ./publish

    - name: Compress Output to ZIP
      run: Compress-Archive -Path ./publish/* -DestinationPath ./build-package.zip
      shell: pwsh

    - name: Upload build package as artifact
      uses: actions/upload-artifact@v4
      with:
        name: build-package
        path: ./build-package.zip

    - name: Download Artifact
      uses: actions/download-artifact@v4
      with:
        name: build-package
        path: ./downloaded-artifacts

    - name: Store ZIP in Temp Folder
      run: |
        $artifactPath = "$env:GITHUB_WORKSPACE\downloaded-artifacts\build-package.zip"
        $tempFolder = "D:\Publish\TempExtract\"

        Write-Host "Checking if temp folder exists at $tempFolder"
        if (!(Test-Path $tempFolder)) { 
          Write-Host "Creating temp folder"
          New-Item -ItemType Directory -Path $tempFolder 
        }

        Write-Host "Copying build-package.zip to temp folder"
        Copy-Item -Path $artifactPath -Destination $tempFolder -Force

        Write-Host "Verifying file in temp folder:"
        Get-ChildItem -Path $tempFolder

        Write-Host "ZIP package has been copied to $tempFolder for later deployment"
      shell: pwsh
