name: Build, Package, and Deploy

on:
  push:
    branches:
      - master

jobs:
  build-package:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0'

    - name: Restore Dependencies
      run: dotnet restore

    - name: Build Project
      run: dotnet build --configuration Release --no-restore

    - name: Publish Project
      run: dotnet publish --configuration Release --output ./publish

    - name: Compress Output to ZIP
      run: |
        Compress-Archive -Path ./publish/* -DestinationPath ./build-package.zip
      shell: pwsh

    - name: Verify File Before Upload
      run: |
        Write-Host "Verifying that the ZIP file exists before upload"
        Test-Path ./build-package.zip
      shell: pwsh

    - name: Upload Build Package as Artifact
      uses: actions/upload-artifact@v4.6.0
      with:
        name: build-package
        path: ./build-package.zip
        if-no-files-found: error
        overwrite: true
        include-hidden-files: false

  deploy-package:
    runs-on: windows-latest
    needs: build-package

    steps:
    - name: Download Build Artifact
      uses: actions/download-artifact@v4.1.8
      with:
        name: build-package
        path: ./artifact-download
        merge-multiple: false

    - name: Verify Artifact After Download
      run: |
        Write-Host "Verifying downloaded artifact..."
        Get-ChildItem ./artifact-download
        Write-Host "Downloaded files:"
        Get-ChildItem ./artifact-download -Recurse | Select-Object Name, Length
      shell: pwsh

    - name: Store ZIP in Temp Folder
      run: |
        $artifactPath = "$env:GITHUB_WORKSPACE\artifact-download\build-package.zip"
        $tempFolder = "D:\Publish\TempExtract\"

        if (!(Test-Path $tempFolder)) { 
          Write-Host "Creating temp folder"
          New-Item -ItemType Directory -Path $tempFolder 
        }

        Write-Host "Copying build-package.zip to temp folder"
        Copy-Item -Path $artifactPath -Destination $tempFolder -Force

        Write-Host "Verifying file in temp folder:"
        Get-ChildItem -Path $tempFolder
      shell: pwsh
